config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tweets#index'
  resources :tweets do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet  # tweetsテーブルとのアソシエーション
  belongs_to :user  # usersテーブルとのアソシエーション
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
  belongs_to :user
  has_one_attached :image
  has_many :comments
  has_many_attached :images

  def self.search(search)
    if search != ""
      Tweet.where('text LIKE(?)', "%#{search}%")
    else
      Tweet.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def search
    @tweets = Tweet.search(params[:keyword])
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/tweets/#{comment.tweet.id}"  
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  PER = 8

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC") #N+1問題を解消
    @pages = Tweet.page(params[:page]).per(PER)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  private
  def tweet_params
    params.require(:tweet).permit(:title, :text, images: []).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @tweets = current_user.tweets.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Original2App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <%= link_to image_tag("logo.png", class: :logo), root_path %>
        <ul class="nav">
          <% if user_signed_in? %>
              <%= current_user.nickname %>
              <%= link_to "Post", new_tweet_path, class: :nav__btn %>
              <%= link_to "Mypage", "/users/#{current_user.id}", class: :nav__btn %>
              <%= link_to "Logout", destroy_user_session_path, class: :nav__btn, method: :delete %>
          <% else %>
              <%= link_to "Login", new_user_session_path, class: :nav__btn %>
              <%= link_to "Signup", new_user_registration_path, class: :nav__btn %>
          <% end %>
        </ul>
          <%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
            <%= form.text_field :keyword, placeholder: "Title", class: "search-input" %>
            <%= form.submit "Search", class: "nav__btn" %>
          <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <div class="footer copyright">
        Copyright Original 2021.
      </div>
    </footer>
  </body>
</html>

app/views/tweets/_form.html.erb
<div class="form__center">
  <div class="form__wrapper">
    <% @tweet.images.each do |image| %>
      <%= image_tag image.variant(resize: '300x300'), class: 'images' %>
    <% end %>
    <%= form_with(model: @tweet, local: true) do |form| %>
    <div id="image-list"></div>
      <%= form.file_field :images, name: 'tweet[images][]', id: 'tweet_image' %><br>
      <p><%= form.text_field :title, placeholder: "Title" %></p>
      <p><%= form.text_area :text, placeholder: "Diary", rows: "3" %></p>
      <p><%= form.submit "SEND", class: :form__btn %></p>
    <% end %>
  </div>
</div>

app/views/tweets/_tweet.html.erb
<div class="card">
  <%= link_to 'show', tweet_path(tweet.id), class: :card__btn, method: :get %>
  <%= link_to 'Edit', edit_tweet_path(tweet.id), class: :card__btn, method: :get %>
  <%= link_to 'Delete', tweet_path(tweet.id), class: :card__btn, method: :delete %><br>
  <%= "Name:#{tweet.user.nickname}" %><br>
  <%= "Title: #{tweet.title}" %><br>     
  <% tweet.images.first(1).each do |image| %>
    <%= image_tag image.variant(resize: '300x300'), class: "tweet-img" %>
  <% end %>
</div>

app/views/tweets/create.html.erb
<h3>Post completion</h3>
<%= link_to "Back", href="/", class: :card__user %>

app/views/tweets/destroy.html.erb
<h3>Delete completion</h3>
<%= link_to "Back", href="/", class: :card__user %>

app/views/tweets/edit.html.erb
<h4>Edit<%= link_to "Back", href="/", class: :card__user %></h4>
<%= render partial: "form", locals: { tweet: @tweet } %>

app/views/tweets/index.html.erb
<div class="card__summary">
  <div class="card__wrapper">
    <% @tweets.each do |tweet| %>
      <%= render partial: "tweets/tweet", locals: { tweet: tweet } %>
    <% end %>
  </div>
  <%= paginate @pages %>
</div>

app/views/tweets/new.html.erb
<h3>Post</h3>
<%= render partial: "form", locals: { tweet: @tweet } %>    

app/views/tweets/search.html.erb
 <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>

app/views/tweets/show.html.erb
<div class="main__center">
  <%= link_to 'Edit', edit_tweet_path(@tweet.id), class: :nav__btn, class: :nav__btn, method: :get %>
  <%= link_to 'Delete', tweet_path(@tweet.id), class: :nav__btn, method: :delete %><br>
  <% @tweet.images.each do |image| %>
    <%= image_tag image.variant(resize: '500x500'), class:'images' %><br>
  <% end %>
  <%= @tweet.updated_at.strftime('%Y/%m/%d %H:%M:%S') %><br>
  <strong><%= "Title: #{@tweet.title}" %></strong><br>  
  <strong><%= "Diary: #{@tweet.text}" %></strong><br>
  <div class="container">
      <% if user_signed_in? %>
        <%= form_with(model: [@tweet, @comment], local: true) do |form| %>
          <%= form.text_area :text, placeholder: "comment", rows: "1" %>
          <%= form.submit "SEND",class: :card__btn %>
        <% end %>
      <% else %>
        <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
      <% end %>
      <div class="comments">
        <h3>comments</h3>
        <% @comments.each do |comment| %>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      </div>
  </div>
</div>
 

app/views/tweets/update.html.erb
<h3>Uodate completion</h3>
<%= link_to "Back", href="/", class: :card__user %>

app/views/users/show.html.erb
 <p><%= @nickname %>Postlist</p>
 <%= link_to "Back", href="/", class: :card__user %>
  <div class="card__wrapper">
    <% @tweets.each do |tweet| %>
      <div class="card">
        <% tweet.images.first(1).each do |image| %>
         <%= image_tag image.variant(resize: '300x300'), class: "tweet-img" %><br>
        <% end %>
        <%= tweet.updated_at.strftime('%Y/%m/%d %H:%M:%S') %><br> 
        <strong><%= "Title: #{tweet.title}" %></strong><br>  
        <strong><%= "Dialy: #{tweet.text}" %></strong><br>
      </div>
    <% end %>
  </div>